name: Deploy Site

on:
  push:
    branches:
      - test/github-actions

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Install
        run: |
          cd ${HOME}
          pwd
          ls -la
          npm ci

      - name: Build Project
        run: |
          cd ${HOME}
          pwd
          ls -la
          npm run build:prod

      - name: Deploy mdor.dev to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # tool specific
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy specific
          destination_dir: ./
          publish_dir: ./docs
          publish_branch: mdor-page
          # page specific
          cname: mdor.dev
