name: Deploy Site

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          npm ci

      - name: Build Project
        run: |
          npm run build:prod

      - name: Deploy mdor.dev to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # tool specific
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy specific
          destination_dir: ./
          publish_dir: ./docs
          publish_branch: mdor-page
          # page specific
          cname: mdor.dev
