name: Validate New Content

on: [pull_request]

jobs:
  validate-content:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          npm ci

      - name: Linter
        run: |
          npm run lint

      - name: Build Project - Not Optimized
        run: |
          npm run build
